# Generated by Django 4.2 on 2024-04-25 18:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaking_strength_weft', models.IntegerField(null=True)),
                ('breaking_strength_warp', models.IntegerField(null=True)),
                ('tearing_strength_weft', models.IntegerField(null=True)),
                ('tearing_strength_warp', models.IntegerField(null=True)),
                ('elasticity', models.IntegerField(null=True)),
                ('pot', models.IntegerField(null=True)),
                ('cielab_l', models.IntegerField(null=True)),
                ('cielab_a', models.IntegerField(null=True)),
                ('cielab_b', models.IntegerField(null=True)),
                ('stiffness', models.IntegerField(null=True)),
                ('alambeta', models.IntegerField(null=True)),
                ('recovery', models.IntegerField(null=True)),
                ('pilling', models.IntegerField(null=True)),
                ('contact_angle', models.IntegerField(null=True)),
                ('air_permeability', models.IntegerField(null=True)),
                ('abrasion_resistance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('bleaching', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('duration', models.IntegerField(choices=[(5, 5), (6, 6), (7, 7)], default=5)),
                ('temperature', models.IntegerField(default=50)),
                ('concentration', models.IntegerField(choices=[(4000, 4000), (5000, 5000), (6000, 6000), (7000, 7000)], default=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.IntegerField(default=1)),
                ('raw_image', models.ImageField(null=True, upload_to='raw/')),
                ('output_images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(null=True, upload_to='output/'), null=True, size=None)),
                ('quality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataops.quality')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataops.recipe')),
            ],
        ),
    ]
