# Generated by Django 4.2 on 2024-05-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0002_alter_experiment_output_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('type', models.IntegerField(primary_key=True, serialize=False)),
                ('material', models.CharField(null=True)),
                ('material_text', models.CharField(null=True)),
                ('coloring', models.CharField(null=True)),
                ('coloring_type', models.CharField(choices=[('halat', 'halat'), ('Slasher', 'Slasher'), ('indigo', 'indigo'), ('Vat dye', 'Vat dye')])),
                ('elastan', models.CharField(null=True)),
                ('elasticity', models.IntegerField(null=True)),
                ('composition', models.CharField(null=True)),
                ('yarn_number', models.FloatField(null=True)),
                ('frequency', models.FloatField(null=True)),
                ('knitting', models.CharField(null=True)),
                ('onyzd', models.FloatField(null=True)),
                ('onyzd_washed', models.FloatField(null=True)),
                ('product_color', models.CharField(null=True)),
                ('width', models.CharField(null=True)),
            ],
        ),
    ]
