# Generated by Django 4.2 on 2024-05-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0003_fabric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='type',
            new_name='id',
        ),
    ]
