# Generated by Django 4.2 on 2024-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0009_alter_experiment_cielab_a_alter_experiment_cielab_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
