# Generated by Django 4.2 on 2024-05-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0010_alter_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
