# Generated by Django 5.0.7 on 2024-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0014_remove_experiment_output_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='knitting',
            field=models.CharField(choices=[('2/1 Z', '2/1 Z'), ('3/1 Z', '3/1 Z'), ('3/1 RHT', '3/1 RHT'), ('4/1 SATEN 3 ATLA', '4/1 SATEN 3 ATLA'), ('3/1 KIRIK DİMİ', '3/1 KIRIK DİMİ')], null=True),
        ),
    ]
