# Generated by Django 5.1.2 on 2024-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0015_alter_fabric_knitting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='elasticity',
            new_name='fabric_elasticity',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='coloring',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='elastan',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='material',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='material_text',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='onyzd_washed',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='width',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='temperature',
        ),
        migrations.AddField(
            model_name='experiment',
            name='breaking_strength_warp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='breaking_strength_weft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='breaking_strength_warp_hypo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='breaking_strength_warp_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='breaking_strength_weft_hypo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='breaking_strength_weft_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
