# Generated by Django 5.1.2 on 2024-11-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataops', '0016_rename_elasticity_fabric_fabric_elasticity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='onyzd',
            new_name='onzyd',
        ),
    ]
