util = {"gramaj_raw": "gramaj_raw",
        "gramaj_hypo": "gramaj_hypo",
        "gramaj_post_hypo": "gramaj",  

        "elasticity_raw": "elasticity_raw",
        "elasticity_hypo": "elasticity_hypo",
        "elasticity_post_hypo": "elasticity",

        "pot_raw": "pot_raw",
        "pot_hypo": "pot_hypo",
        "pot_post_hypo": "pot",

        "cielab_l_raw": "cielab_l_raw",
        "cielab_l_hypo": "cielab_l_hypo",
        "cielab_l_post_hypo": "cielab_l",
        "cielab_a_raw": "cielab_a_raw",
        "cielab_a_hypo": "cielab_a_hypo",
        "cielab_a_post_hypo": "cielab_a",
        "cielab_b_raw": "cielab_b_raw",
        "cielab_b_hypo": "cielab_b_hypo",
        "cielab_b_post_hypo": "cielab_b",

        "tearing_weft_raw": "tearing_strength_weft_raw",
        "tearing_weft_hypo": "tearing_strength_weft_hypo",
        "tearing_weft_post_hypo": "tearing_strength_weft",
        "tearing_warp_raw": "tearing_strength_warp_raw",
        "tearing_warp_hypo": "tearing_strength_warp_hypo",
        "tearing_warp_post_hypo": "tearing_strength_warp",

        "breaking_weft_raw": "breaking_strength_weft_raw",
        "breaking_weft_hypo": "breaking_strength_weft_hypo",
        "breaking_weft_post_hypo": "breaking_strength_weft",
        "breaking_warp_raw": "breaking_strength_warp_raw",
        "breaking_warp_hypo": "breaking_strength_warp_hypo",
        "breaking_warp_post_hypo": "breaking_strength_warp",

        "bleaching_num": "bleaching",
        "duration": "duration",
        "concentration": "concentration",

        "type": "id",

        "coloring_type": "coloring_type",
        "onyzd": "onyzd",
        "yarn": "yarn_number",
        "frequency": "frequency",
        "knitting": "knitting",
        "elasticity": "fabric_elasticity"}

utility = {"weft_target": "cont",
        "warp_target": "cont",
        "elasticity_target": "cont",
        "pot_target": "cont",
        "cielab_l_target": "cont",
        "cielab_a_target": "cont",
        "cielab_b_target": "cont",
        "gramaj_raw": "cont",
        "gramaj_hypo": "cont", 
        "weft_raw": "cont",
        "weft_hypo": "cont",
        "warp_raw": "cont",
        "warp_hypo": "cont",
        "elasticity_raw": "cont",
        "elasticity_hypo": "cont",
        "pot_raw": "cont",
        "pot_hypo": "cont",
        "cielab_l_raw": "cont",
        "cielab_l_hypo": "cont",
        "cielab_a_raw": "cont",
        "cielab_a_hypo": "cont",
        "cielab_b_raw": "cont",
        "cielab_b_hypo": "cont",
        "bleaching_num": "cont",
        "duration": "cont",
        "concentration": "cont",
        "type": "discrete",
        "coloring": "discrete",
        "coloring_type": "discrete",
        "onyzd": "cont",
        "yarn": "cont",
        "frequency": "cont",
        "knitting": "discrete"}