labels = {"coloring_type": "Boyama Tipi",
         "onzyd": "Onz/yd2",
        "yarn_number": "İplik No (ne)",
        "fabric_elasticity": "Elastanlık",
        "frequency": "Sıklık",
        "knitting": "Örgü",
        "elasticity_raw": "Elastikiyet (ham)",
        "elasticity_hypo": "Elastikiyet (hipo öncesi)",
        "elasticity": "Elastikiyet (hipo sonrası)",
        "pot_raw": "Potluk (ham)",
        "pot_hypo": "Potluk (hipo öncesi)",
        "pot": "Potluk (hipo sonrası)",
        "gramaj_raw": "Gramaj (ham)",
        "gramaj_hypo": "Gramaj (hipo öncesi)",
        "gramaj": "Gramaj (hipo sonrası)",
        "cielab_l_raw": "CIELab L* (ham)",
        "cielab_l_hypo": "CIELab L* (hipo öncesi)",
        "cielab_a_raw": "CIELab a* (ham)",
        "cielab_a_hypo": "CIELab a* (hipo öncesi)",
        "cielab_b_raw": "CIELab b* (ham)",
        "cielab_b_hypo": "CIELab b* (hipo öncesi)",
        "bleaching": "Ağartma Sayısı",
        "duration": "Süre",
        "concentration": "Konsantrasyon",
        "cielab_l": "CIELab L*",
        "cielab_a": "CIELab a*",
        "cielab_b": "CIELab b*",
        "tearing_strength_weft_raw": "Yırtılma Mukavemeti (atkı) (ham)",
        "tearing_strength_weft_hypo": "Yırtılma Mukavemeti (atkı) (hipo öncesi)",
        "tearing_strength_weft": "Yırtılma Mukavemeti (atkı) (hipo sonrası)",
        "tearing_strength_warp_raw": "Yırtılma Mukavemeti (çözgü) (ham)",
    	"tearing_strength_warp_hypo": "Yırtılma Mukavemeti (çözgü) (hipo öncesi)",
    	"tearing_strength_warp": "Yırtılma Mukavemeti (çözgü) (hipo sonrası)",
        "breaking_strength_weft_raw": "Kopma Mukavemeti (atkı) (ham)",
        "breaking_strength_weft_hypo":	"Kopma Mukavemeti (atkı) (hipo öncesi)",
        "breaking_strength_weft": "Kopma Mukavemeti (atkı) (hipo sonrası)",
        "breaking_strength_warp_raw": "Kopma Mukavemeti (çözgü) (ham)",
        "breaking_strength_warp_hypo":	"Kopma Mukavemeti (çözgü) (hipo öncesi)",
        "breaking_strength_warp": "Kopma Mukavemeti (çözgü) (hipo sonrası)"}

ct_options = {"halat": "halat",
              "Slasher":"Slasher",
              "indigo": "indigo",
              "Vat dye": "Vat dye",
              "2/1 Z": "2/1 Z",
              "3/1 KIRIK DİMİ": "3/1 KIRIK DİMİ",
              "3/1 KIRIK D M ": "3/1 KIRIK DİMİ",
              "3/1 RHT": "3/1 RHT",
              "3/1 Z": "3/1 Z",
              "4/1 SATEN 3 ATLA": "4/1 SATEN 3 ATLA"
              }